# Generated by Django 5.0.1 on 2025-10-06 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('VIEW_LOCATION', 'Viewed Location'), ('ACKNOWLEDGE_ALERT', 'Acknowledged Alert'), ('RESOLVE_ALERT', 'Resolved Alert'), ('SEND_MESSAGE', 'Sent Message'), ('CALL_USER', 'Called User'), ('VIEW_ANALYTICS', 'Viewed Analytics')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuardianDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_location_map', models.BooleanField(default=True)),
                ('show_device_status', models.BooleanField(default=True)),
                ('show_recent_activity', models.BooleanField(default=True)),
                ('show_analytics', models.BooleanField(default=True)),
                ('alert_sound_enabled', models.BooleanField(default=True)),
                ('alert_vibration_enabled', models.BooleanField(default=True)),
                ('auto_refresh_interval', models.IntegerField(default=30, help_text='Auto refresh interval in seconds')),
                ('default_zoom_level', models.IntegerField(default=15)),
                ('show_geofences', models.BooleanField(default=True)),
                ('show_route_history', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuardianNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SOS_ALERT', 'SOS Alert'), ('LOCATION_UPDATE', 'Location Update'), ('DEVICE_OFFLINE', 'Device Offline'), ('LOW_BATTERY', 'Low Battery'), ('GEOFENCE_EXIT', 'Geofence Exit'), ('DAILY_SUMMARY', 'Daily Summary')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guardian', 'is_read'], name='guardians_g_guardia_a9bb23_idx'), models.Index(fields=['notification_type', 'created_at'], name='guardians_g_notific_c9181d_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuardianRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('FAMILY', 'Family Member'), ('FRIEND', 'Friend'), ('CARETAKER', 'Caretaker'), ('PROFESSIONAL', 'Professional Caregiver'), ('OTHER', 'Other')], max_length=15)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_sos', models.BooleanField(default=True)),
                ('notify_location', models.BooleanField(default=True)),
                ('notify_device_status', models.BooleanField(default=True)),
                ('notify_daily_summary', models.BooleanField(default=True)),
                ('preferred_contact_method', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('CALL', 'Phone Call')], default='SMS', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
                'unique_together': {('user', 'guardian')},
            },
        ),
    ]
