# Generated by Django 5.0.1 on 2025-10-06 01:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Smart Blind Stick', max_length=100)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error')], default='OFFLINE', max_length=15)),
                ('battery_level', models.IntegerField(default=0, help_text='Battery percentage (0-100)')),
                ('firmware_version', models.CharField(default='1.0.0', max_length=20)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('ultrasonic_sensor_status', models.BooleanField(default=True)),
                ('infrared_sensor_status', models.BooleanField(default=True)),
                ('gps_sensor_status', models.BooleanField(default=True)),
                ('vibration_motor_status', models.BooleanField(default=True)),
                ('speaker_status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('SYNC', 'Device Sync'), ('BATTERY', 'Battery Update'), ('SENSOR', 'Sensor Status'), ('ERROR', 'Error'), ('CONFIG', 'Configuration Change'), ('SOS', 'SOS Alert'), ('LOCATION', 'Location Update')], max_length=10)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_volume', models.IntegerField(default=70, help_text='Volume level (0-100)')),
                ('audio_enabled', models.BooleanField(default=True)),
                ('voice_guidance', models.BooleanField(default=True)),
                ('vibration_intensity', models.IntegerField(default=70, help_text='Vibration intensity (0-100)')),
                ('vibration_enabled', models.BooleanField(default=True)),
                ('obstacle_detection_range', models.IntegerField(default=200, help_text='Detection range in cm')),
                ('head_level_detection', models.BooleanField(default=True)),
                ('ground_level_detection', models.BooleanField(default=True)),
                ('pothole_detection', models.BooleanField(default=True)),
                ('sos_enabled', models.BooleanField(default=True)),
                ('low_battery_alert', models.BooleanField(default=True)),
                ('device_offline_alert', models.BooleanField(default=True)),
                ('location_tracking', models.BooleanField(default=True)),
                ('location_update_interval', models.IntegerField(default=30, help_text='Update interval in seconds')),
                ('geofencing_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='devices.device')),
            ],
        ),
    ]
